version: "3.7"

volumes:
  docker_application_mysql:

services:
  docker-app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: application
    container_name: docker-application
    working_dir: /var/www/
    volumes:
      - './src:/var/www'
    depends_on:
      - docker-db
  docker-db:
    image: mariadb:10.2
    container_name: docker-application-database
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_ROOT_PASSWORD: database_root_password
      MYSQL_PASSWORD: database_password
      MYSQL_USER: database_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - docker_application_mysql:/var/lib/mysql
  docker-nginx:
    image: nginx:1.17-alpine
    container_name: docker-application-nginx
    ports:
      - "80:80"
    volumes:
      - './src/web:/var/www/web'
      - './docker/default.conf:/etc/nginx/conf.d/default.conf'
  docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: docker-application-phpmyadmin
    environment:
      PMA_HOST: docker-application-database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: database_root_password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    depends_on:
      - docker-db
